databases:
  - name: threadstadon
    databaseName: threadstadon
    user: threadstadon

services:
  - type: web
    name: threadstadon
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: threadstadon
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false