databases:
  - name: threadstadon-staging
    databaseName: threadstadon-staging
  - name: threadstadon
    databaseName: threadstadon
    user: threadstadon
    region: ohio

services:
  - type: web
    name: threadstadon-staging
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: threadstadon-staging
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: web
    name: threadstadon
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    region: ohio
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: threadstadon
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false